[project]
name = "repl-nix-dmr-cycle"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "flask-login>=0.6.3",
    "flask>=3.1.0",
    "sqlalchemy>=2.0.36",
]
